CREATE TABLE PURCHASEINFO(
	PurchaseInfoID	INTEGER NOT NULL PRIMARY KEY 
	,Purchase_modality	INTEGER NOT NULL
	,Ticket_type 	INTEGER NOT NULL
);

INSERT INTO PURCHASEINFO VALUES (1, 1, 1);
INSERT INTO PURCHASEINFO VALUES (2, 2, 2);
INSERT INTO PURCHASEINFO VALUES (3, 3, 3);
INSERT INTO PURCHASEINFO VALUES (4, 1, 2);
INSERT INTO PURCHASEINFO VALUES(5, 1, 3);
INSERT INTO PURCHASEINFO VALUES (6, 2, 1);
INSERT INTO PURCHASEINFO VALUES (7, 2, 3);
INSERT INTO PURCHASEINFO VALUES (8, 3, 1);
INSERT INTO PURCHASEINFO VALUES (9, 3, 2);