CREATE TABLE Tickets(
	MuseumID	INTEGER NOT NULL,
	TimeID	INTEGER NOT NULL,
	PurchaseInfoID	INTEGER NOT NULL,
	Quantity	INTEGER NOT NULL,
	TotalAmount 	INTEGER NOT NULL,
	PRIMARY KEY(MuseumID, TimeID, PurchaseInfoID)
	, FOREIGN KEY(MuseumID) REFERENCES MUSEUM(MuseumID)
	, FOREIGN KEY(TimeID) REFERENCES TIMEDIM(TimeID)
	, FOREIGN KEY(PurchaseInfoID) REFERENCES PURCHASEINFO(PurchaseInfoID)
);

INSERT INTO Tickets VALUES (1, 1, 1, 2, 30);
INSERT INTO Tickets VALUES (2, 1, 1, 1, 15);
INSERT INTO Tickets VALUES (3, 3, 2, 3, 45);
INSERT INTO Tickets VALUES (3, 4, 2, 4, 60);
INSERT INTO Tickets VALUES (4, 1, 3, 2, 30);
INSERT INTO Tickets VALUES (6, 6, 3, 1, 15);
INSERT INTO Tickets VALUES (7, 7, 4, 2, 30);
INSERT INTO Tickets VALUES (8, 8, 4, 3, 45);
INSERT INTO Tickets VALUES (9, 9, 5, 4, 60);
INSERT INTO Tickets VALUES (10, 10, 5, 2, 30);
INSERT INTO Tickets VALUES (10, 11, 6, 1, 15);
INSERT INTO Tickets VALUES (10, 12, 6, 2, 30);
INSERT INTO Tickets VALUES (3, 13, 7, 3, 45);
INSERT INTO Tickets VALUES (4, 14, 7, 4, 60);
INSERT INTO Tickets VALUES (5, 15, 8, 2, 30);
INSERT INTO Tickets VALUES (6, 1, 8, 1, 15);
INSERT INTO Tickets VALUES (7, 1, 9, 3, 45);
INSERT INTO Tickets VALUES (8, 8, 9, 4, 60);
INSERT INTO Tickets VALUES (9, 1, 1, 2, 30);
INSERT INTO Tickets VALUES (2, 13, 9, 1, 15);
